apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app-cli-1
  name: python-app-cli-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-cli-1
  template:
    metadata:
      labels:
        app: python-app-cli-1
    spec:
      #nodeSelector:
      #  lifecycle: Ec2Spot
      containers:
      - env:
        - name: TCPCMD
          value: "pong1"
        image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/python-socket-psql-sample:0.2
        imagePullPolicy: Always
        name: python-socket-psql-sample
        command: ["/start-cli.sh"]
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
